#!/bin/bash

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

FORMAT_JAR_LOCATION="${REPO_ROOT_DIR}/tools/java-format/google-java-format-1.5-all-deps.jar"

for staged_file in $(git diff --cached --name-only); do
  [ -f "${staged_file}" ] || continue

  "${REPO_ROOT_DIR}/scripts/check-java-file-format" "${FORMAT_JAR_LOCATION}" "${staged_file}"
  git add "${staged_file}"
done
