package org.sunbird.telemetry.dto;

import java.util.HashMap;
import java.util.Map;

/**
 * Represents a Backend (BE) Telemetry Event.
 * This class captures telemetry data generated by backend services.
 */
public class TelemetryBEEvent {

  private String eid;
  private long ets;
  private String mid;
  private String ver;
  private String channel;
  private Map<String, String> pdata;
  private Map<String, Object> edata;

  /**
   * Gets the event ID.
   *
   * @return the eid
   */
  public String getEid() {
    return eid;
  }

  /**
   * Sets the event ID.
   *
   * @param eid the eid to set
   */
  public void setEid(String eid) {
    this.eid = eid;
  }

  /**
   * Gets the event timestamp.
   *
   * @return the ets
   */
  public long getEts() {
    return ets;
  }

  /**
   * Sets the event timestamp.
   *
   * @param ets the ets to set
   */
  public void setEts(long ets) {
    this.ets = ets;
  }

  /**
   * Gets the version.
   *
   * @return the ver
   */
  public String getVer() {
    return ver;
  }

  /**
   * Sets the version.
   *
   * @param ver the ver to set
   */
  public void setVer(String ver) {
    this.ver = ver;
  }

  /**
   * Gets the producer data.
   *
   * @return the pdata
   */
  public Map<String, String> getPdata() {
    return pdata;
  }

  /**
   * Sets the producer data.
   *
   * @param pdata the pdata to set
   */
  public void setPdata(Map<String, String> pdata) {
    this.pdata = pdata;
  }

  /**
   * Gets the event data.
   *
   * @return the edata
   */
  public Map<String, Object> getEdata() {
    return edata;
  }

  /**
   * Sets the event data with specific eks map.
   *
   * @param eks the eks map to be put inside edata
   */
  public void setEdata(Map<String, Object> eks) {
    this.edata = new HashMap<>();
    edata.put("eks", eks);
  }

  /**
   * Sets the producer data with specific fields.
   *
   * @param id  Producer ID
   * @param pid Producer PID
   * @param ver Producer Version
   * @param uid User ID (Note: unused in implementation but present in signature)
   */
  public void setPdata(String id, String pid, String ver, String uid) {
    this.pdata = new HashMap<>();
    this.pdata.put("id", id);
    this.pdata.put("pid", pid);
    this.pdata.put("ver", ver);
  }

  /**
   * Sets edata for Content events.
   *
   * @param cid        Content ID
   * @param status     Content Status
   * @param prevState  Previous State
   * @param size       Size
   * @param pkgVersion Package Version
   * @param concepts   Concepts
   */
  public void setEdata(
      String cid,
      Object status,
      Object prevState,
      Object size,
      Object pkgVersion,
      Object concepts) {
    this.edata = new HashMap<>();
    Map<String, Object> eks = new HashMap<>();
    eks.put("cid", cid);
    eks.put("state", status);
    eks.put("prevstate", prevState);
    eks.put("size", size);
    eks.put("pkgVersion", pkgVersion);
    eks.put("concepts", concepts);
    edata.put("eks", eks);
  }

  /**
   * Sets edata for Search events.
   *
   * @param query         Search query
   * @param filters       Search filters
   * @param sort          Search sort order
   * @param correlationId Correlation ID
   * @param size          Result size
   */
  public void setEdata(String query, Object filters, Object sort, String correlationId, int size) {
    this.edata = new HashMap<>();
    Map<String, Object> eks = new HashMap<>();
    eks.put("query", query);
    eks.put("filters", filters);
    eks.put("sort", sort);
    eks.put("correlationid", correlationId);
    eks.put("size", size);
    edata.put("eks", eks);
  }

  /**
   * Sets edata for Lifecycle/State change events.
   *
   * @param id        Target ID
   * @param state     Current State
   * @param prevState Previous State
   * @param lemma     Lemma (used in wordnet/language) or auxiliary data
   */
  public void setEdata(String id, Object state, Object prevState, Object lemma) {
    this.edata = new HashMap<>();
    Map<String, Object> eks = new HashMap<>();
    eks.put("id", id);
    eks.put("state", state);
    eks.put("prevstate", prevState);
    eks.put("lemma", lemma);
    edata.put("eks", eks);
  }

  /**
   * Gets the message ID.
   *
   * @return the mid
   */
  public String getMid() {
    return mid;
  }

  /**
   * Sets the message ID.
   *
   * @param mid the mid to set
   */
  public void setMid(String mid) {
    this.mid = mid;
  }

  /**
   * Gets the channel ID.
   *
   * @return the channel, or empty string if null
   */
  public String getChannel() {
    if (null == channel) {
      channel = "";
    }
    return channel;
  }

  /**
   * Sets the channel ID.
   *
   * @param channel the channel to set
   */
  public void setChannel(String channel) {
    String tempChannel = channel;
    if (null == channel) {
      tempChannel = "";
    }
    this.channel = tempChannel;
  }
}
